CREATE TABLE "assets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"brand" text,
	"product" text,
	"type" text,
	"visual_keyword" text,
	"file_id" text,
	"file_name" text,
	"file_format" text,
	"file_size" text,
	"file_dimensions" text,
	"comment" text,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
CREATE TABLE "audiences" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audiences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"key" text NOT NULL,
	"name" text NOT NULL,
	"order_index" integer NOT NULL,
	"status" text,
	"product" text,
	"strategy" text,
	"buying_platform" text,
	"data_source" text,
	"targeting_type" text,
	"device" text,
	"tag" text,
	"comment" text,
	"campaign_name" text,
	"campaign_id" text,
	"lineitem_name" text,
	"lineitem_id" text,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"user_id" text,
	"entity_type" text NOT NULL,
	"entity_id" text NOT NULL,
	"action" text NOT NULL,
	"before" text,
	"after" text,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "clients" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clients_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" text NOT NULL,
	"name" text NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"mcp_token" text,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	CONSTRAINT "clients_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "config" (
	"client_id" integer NOT NULL,
	"key" text NOT NULL,
	"value" text NOT NULL,
	"category" text,
	"description" text,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	CONSTRAINT "config_client_id_key_pk" PRIMARY KEY("client_id","key")
);
--> statement-breakpoint
CREATE TABLE "creatives" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "creatives_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"brand" text,
	"product" text,
	"type" text,
	"visual_keyword" text,
	"copy_keyword" text,
	"template" text,
	"banner_version" text,
	"mc_number" integer,
	"mc_variant" text,
	"file_id" text,
	"file_name" text,
	"file_format" text,
	"file_size" text,
	"file_dimensions" text,
	"family_key" text,
	"comment" text,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
CREATE TABLE "feed_exports" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "feed_exports_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"product" text NOT NULL,
	"feed_version" integer NOT NULL,
	"exported_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"exported_by" text,
	"uploaded_to_adform_at" text,
	"uploaded_by" text,
	"default_message_id" integer,
	"default_label" text,
	"row_count" integer NOT NULL,
	"payload_json" text NOT NULL,
	"notes" text,
	"source" text DEFAULT 'export' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "keywords" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "keywords_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"form" text NOT NULL,
	"field" text NOT NULL,
	"value" text NOT NULL,
	"order_index" integer DEFAULT 0 NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"number" integer NOT NULL,
	"variant" text NOT NULL,
	"audience" text NOT NULL,
	"topic" text NOT NULL,
	"version_no" integer DEFAULT 1 NOT NULL,
	"pmmid" text,
	"status" text,
	"start_date" text,
	"end_date" text,
	"template" text,
	"template_variant_classes" text,
	"name" text,
	"headline" text,
	"copy1" text,
	"copy2" text,
	"disclaimer" text,
	"headline_style" text,
	"copy1_style" text,
	"copy2_style" text,
	"disclaimer_style" text,
	"cta_style" text,
	"custom_css" text,
	"image1" text,
	"image2" text,
	"image3" text,
	"image4" text,
	"image5" text,
	"image6" text,
	"video1" text,
	"flash" text,
	"flash_style" text,
	"cta" text,
	"landing_url" text,
	"comment" text,
	"utm_campaign" text,
	"utm_source" text,
	"utm_medium" text,
	"utm_content" text,
	"utm_term" text,
	"utm_cd26" text,
	"final_trafficked_url" text,
	"brief" text,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
CREATE TABLE "monitoring" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monitoring_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"platform" text NOT NULL,
	"scope" text,
	"pmmid" text,
	"message_id" integer,
	"product" text,
	"size" text DEFAULT '' NOT NULL,
	"audience_key" text NOT NULL,
	"topic_key" text NOT NULL,
	"mc_number" integer NOT NULL,
	"mc_variant" text NOT NULL,
	"impressions" integer DEFAULT 0 NOT NULL,
	"clicks" integer DEFAULT 0 NOT NULL,
	"cost" real DEFAULT 0 NOT NULL,
	"conversions" integer DEFAULT 0 NOT NULL,
	"ctr" real,
	"period_from" text NOT NULL,
	"period_to" text NOT NULL,
	"imported_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"source_filename" text
);
--> statement-breakpoint
CREATE TABLE "reporting" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reporting_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"level" text NOT NULL,
	"mc_label" text,
	"size" text,
	"banner_id" text,
	"banner_name" text,
	"adform_status" text,
	"impressions" integer DEFAULT 0 NOT NULL,
	"clicks" integer DEFAULT 0 NOT NULL,
	"ctr" real,
	"campaign_id" text,
	"campaign_name" text,
	"synced_at" text,
	"archived_at" text
);
--> statement-breakpoint
CREATE TABLE "share_comments" (
	"id" text PRIMARY KEY NOT NULL,
	"share_gallery_id" text NOT NULL,
	"item_key" text NOT NULL,
	"author_name" text NOT NULL,
	"body" text NOT NULL,
	"annotation" text,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
CREATE TABLE "share_galleries" (
	"id" text PRIMARY KEY NOT NULL,
	"client_id" integer NOT NULL,
	"title" text,
	"description" text,
	"created_by" text,
	"metadata" text,
	"view_count" integer DEFAULT 0 NOT NULL,
	"download_count" integer DEFAULT 0 NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
CREATE TABLE "snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"label" text NOT NULL,
	"created_by" text,
	"payload_json" text NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "system_config" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"description" text,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "text_formatting" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "text_formatting_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"text_original" text NOT NULL,
	"text_formatted" text NOT NULL,
	"formatting_scope" text,
	"formatting_mc_scope" text,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
CREATE TABLE "topics" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "topics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"key" text NOT NULL,
	"name" text NOT NULL,
	"order_index" integer NOT NULL,
	"status" text,
	"product" text,
	"tag" text,
	"tag1" text,
	"tag2" text,
	"tag3" text,
	"tag4" text,
	"comment" text,
	"created" text,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
CREATE TABLE "uploaded_files" (
	"id" text PRIMARY KEY NOT NULL,
	"client_id" integer NOT NULL,
	"filename" text NOT NULL,
	"original_filename" text NOT NULL,
	"storage_path" text NOT NULL,
	"mime_type" text,
	"size_bytes" integer,
	"dimensions" text,
	"sha256" text,
	"uploaded_by" text,
	"category" text NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" text PRIMARY KEY NOT NULL,
	"client_id" integer NOT NULL,
	"email" text NOT NULL,
	"password" text NOT NULL,
	"role" text DEFAULT 'user' NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
ALTER TABLE "assets" ADD CONSTRAINT "assets_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audiences" ADD CONSTRAINT "audiences_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "config" ADD CONSTRAINT "config_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "creatives" ADD CONSTRAINT "creatives_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feed_exports" ADD CONSTRAINT "feed_exports_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "keywords" ADD CONSTRAINT "keywords_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monitoring" ADD CONSTRAINT "monitoring_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monitoring" ADD CONSTRAINT "monitoring_message_id_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."messages"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reporting" ADD CONSTRAINT "reporting_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "share_comments" ADD CONSTRAINT "share_comments_share_gallery_id_share_galleries_id_fk" FOREIGN KEY ("share_gallery_id") REFERENCES "public"."share_galleries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "share_galleries" ADD CONSTRAINT "share_galleries_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "snapshots" ADD CONSTRAINT "snapshots_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "text_formatting" ADD CONSTRAINT "text_formatting_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "topics" ADD CONSTRAINT "topics_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "uploaded_files" ADD CONSTRAINT "uploaded_files_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "assets_client_brand_idx" ON "assets" USING btree ("client_id","brand");--> statement-breakpoint
CREATE INDEX "assets_client_product_idx" ON "assets" USING btree ("client_id","product");--> statement-breakpoint
CREATE INDEX "assets_client_type_idx" ON "assets" USING btree ("client_id","type");--> statement-breakpoint
CREATE INDEX "assets_client_file_idx" ON "assets" USING btree ("client_id","file_id");--> statement-breakpoint
CREATE UNIQUE INDEX "audiences_client_key_unique" ON "audiences" USING btree ("client_id","key");--> statement-breakpoint
CREATE INDEX "audiences_client_product_idx" ON "audiences" USING btree ("client_id","product");--> statement-breakpoint
CREATE INDEX "audiences_client_order_idx" ON "audiences" USING btree ("client_id","order_index");--> statement-breakpoint
CREATE INDEX "audit_client_user_idx" ON "audit_log" USING btree ("client_id","user_id");--> statement-breakpoint
CREATE INDEX "audit_client_entity_idx" ON "audit_log" USING btree ("client_id","entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "audit_client_created_idx" ON "audit_log" USING btree ("client_id","created_at");--> statement-breakpoint
CREATE INDEX "clients_status_idx" ON "clients" USING btree ("status");--> statement-breakpoint
CREATE INDEX "config_client_category_idx" ON "config" USING btree ("client_id","category");--> statement-breakpoint
CREATE INDEX "creatives_client_brand_idx" ON "creatives" USING btree ("client_id","brand");--> statement-breakpoint
CREATE INDEX "creatives_client_product_idx" ON "creatives" USING btree ("client_id","product");--> statement-breakpoint
CREATE INDEX "creatives_client_file_idx" ON "creatives" USING btree ("client_id","file_id");--> statement-breakpoint
CREATE INDEX "creatives_client_mc_idx" ON "creatives" USING btree ("client_id","mc_number","mc_variant");--> statement-breakpoint
CREATE INDEX "creatives_client_family_idx" ON "creatives" USING btree ("client_id","family_key");--> statement-breakpoint
CREATE INDEX "feed_exports_client_product_idx" ON "feed_exports" USING btree ("client_id","product");--> statement-breakpoint
CREATE INDEX "feed_exports_client_uploaded_idx" ON "feed_exports" USING btree ("client_id","uploaded_to_adform_at");--> statement-breakpoint
CREATE INDEX "feed_exports_client_product_version_idx" ON "feed_exports" USING btree ("client_id","product","feed_version");--> statement-breakpoint
CREATE INDEX "feed_exports_client_source_idx" ON "feed_exports" USING btree ("client_id","source");--> statement-breakpoint
CREATE UNIQUE INDEX "keywords_client_form_field_value_unique" ON "keywords" USING btree ("client_id","form","field","value");--> statement-breakpoint
CREATE INDEX "keywords_client_form_field_order_idx" ON "keywords" USING btree ("client_id","form","field","order_index");--> statement-breakpoint
CREATE INDEX "messages_client_topic_audience_idx" ON "messages" USING btree ("client_id","topic","audience");--> statement-breakpoint
CREATE INDEX "messages_client_status_idx" ON "messages" USING btree ("client_id","status");--> statement-breakpoint
CREATE INDEX "messages_client_number_idx" ON "messages" USING btree ("client_id","number");--> statement-breakpoint
CREATE INDEX "messages_client_pmmid_idx" ON "messages" USING btree ("client_id","pmmid");--> statement-breakpoint
CREATE INDEX "monitoring_client_message_idx" ON "monitoring" USING btree ("client_id","message_id");--> statement-breakpoint
CREATE INDEX "monitoring_client_platform_idx" ON "monitoring" USING btree ("client_id","platform");--> statement-breakpoint
CREATE INDEX "monitoring_client_mc_idx" ON "monitoring" USING btree ("client_id","mc_number","mc_variant");--> statement-breakpoint
CREATE UNIQUE INDEX "monitoring_client_period_key_idx" ON "monitoring" USING btree ("client_id","platform","period_from","period_to","mc_number","mc_variant","audience_key","topic_key","size");--> statement-breakpoint
CREATE INDEX "reporting_client_mc_idx" ON "reporting" USING btree ("client_id","mc_label");--> statement-breakpoint
CREATE INDEX "reporting_client_mc_size_idx" ON "reporting" USING btree ("client_id","mc_label","size");--> statement-breakpoint
CREATE INDEX "reporting_client_level_idx" ON "reporting" USING btree ("client_id","level");--> statement-breakpoint
CREATE INDEX "share_comments_share_idx" ON "share_comments" USING btree ("share_gallery_id");--> statement-breakpoint
CREATE INDEX "share_comments_share_item_idx" ON "share_comments" USING btree ("share_gallery_id","item_key");--> statement-breakpoint
CREATE INDEX "share_galleries_client_idx" ON "share_galleries" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "snapshots_client_created_idx" ON "snapshots" USING btree ("client_id","created_at");--> statement-breakpoint
CREATE INDEX "text_formatting_client_idx" ON "text_formatting" USING btree ("client_id");--> statement-breakpoint
CREATE UNIQUE INDEX "topics_client_key_unique" ON "topics" USING btree ("client_id","key");--> statement-breakpoint
CREATE INDEX "topics_client_product_idx" ON "topics" USING btree ("client_id","product");--> statement-breakpoint
CREATE INDEX "topics_client_order_idx" ON "topics" USING btree ("client_id","order_index");--> statement-breakpoint
CREATE INDEX "uploaded_files_client_sha_idx" ON "uploaded_files" USING btree ("client_id","sha256");--> statement-breakpoint
CREATE INDEX "uploaded_files_client_category_idx" ON "uploaded_files" USING btree ("client_id","category");--> statement-breakpoint
CREATE INDEX "uploaded_files_client_cat_created_idx" ON "uploaded_files" USING btree ("client_id","category","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "users_client_email_unique" ON "users" USING btree ("client_id","email");--> statement-breakpoint
CREATE INDEX "users_client_idx" ON "users" USING btree ("client_id");