CREATE TABLE "message_previews" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "message_previews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"message_id" integer NOT NULL,
	"size" text NOT NULL,
	"storage_key" text NOT NULL,
	"message_version" integer NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "message_previews" ADD CONSTRAINT "message_previews_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_previews" ADD CONSTRAINT "message_previews_message_id_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "message_previews_message_size_unique" ON "message_previews" USING btree ("client_id","message_id","size");--> statement-breakpoint
CREATE INDEX "message_previews_client_message_idx" ON "message_previews" USING btree ("client_id","message_id");