CREATE TABLE "mcp_tokens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mcp_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"token" text NOT NULL,
	"scope" text DEFAULT 'full' NOT NULL,
	"label" text,
	"last_used_at" text,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
ALTER TABLE "mcp_tokens" ADD CONSTRAINT "mcp_tokens_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mcp_tokens" ADD CONSTRAINT "mcp_tokens_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "mcp_tokens_token_unique" ON "mcp_tokens" USING btree ("token");--> statement-breakpoint
CREATE INDEX "mcp_tokens_client_idx" ON "mcp_tokens" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "mcp_tokens_client_user_idx" ON "mcp_tokens" USING btree ("client_id","user_id");--> statement-breakpoint
INSERT INTO "mcp_tokens" ("client_id", "user_id", "token", "scope", "label")
SELECT c."id", u."id", c."mcp_token", 'full', 'Migrated client token'
FROM "clients" c
JOIN LATERAL (
	SELECT "id" FROM "users"
	WHERE "client_id" = c."id" AND "archived_at" IS NULL
	ORDER BY ("role" = 'admin') DESC, "created_at" ASC, "id" ASC
	LIMIT 1
) u ON true
WHERE c."mcp_token" IS NOT NULL;--> statement-breakpoint
ALTER TABLE "clients" DROP COLUMN "mcp_token";