CREATE TABLE "prodlist_rows" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "prodlist_rows_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"deliverable_id" text NOT NULL,
	"production_unit_id" text,
	"channel" text,
	"campaign" text,
	"format" text,
	"required_asset" text,
	"flight_start" text,
	"flight_end" text,
	"source_ref" text,
	"family_key" text,
	"mc_number" integer,
	"mc_variant" text,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
ALTER TABLE "prodlist_rows" ADD CONSTRAINT "prodlist_rows_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "prodlist_rows_client_deliverable_unique" ON "prodlist_rows" USING btree ("client_id","deliverable_id");--> statement-breakpoint
CREATE INDEX "prodlist_rows_client_channel_idx" ON "prodlist_rows" USING btree ("client_id","channel");--> statement-breakpoint
CREATE INDEX "prodlist_rows_client_mc_idx" ON "prodlist_rows" USING btree ("client_id","mc_number","mc_variant");--> statement-breakpoint
CREATE INDEX "prodlist_rows_client_family_idx" ON "prodlist_rows" USING btree ("client_id","family_key");