CREATE TABLE "draft_messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "draft_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"name" text,
	"template" text NOT NULL,
	"template_variant_classes" text,
	"headline" text,
	"copy1" text,
	"copy2" text,
	"disclaimer" text,
	"cta" text,
	"flash" text,
	"headline_style" text,
	"copy1_style" text,
	"copy2_style" text,
	"disclaimer_style" text,
	"cta_style" text,
	"flash_style" text,
	"custom_css" text,
	"image1" text,
	"image2" text,
	"image3" text,
	"image4" text,
	"image5" text,
	"image6" text,
	"sizes" text NOT NULL,
	"render_status" text DEFAULT 'pending' NOT NULL,
	"render_started_at" text,
	"render_error" text,
	"promoted_message_id" integer,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "draft_previews" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "draft_previews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"draft_id" integer NOT NULL,
	"size" text NOT NULL,
	"storage_key" text NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "draft_messages" ADD CONSTRAINT "draft_messages_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "draft_messages" ADD CONSTRAINT "draft_messages_promoted_message_id_messages_id_fk" FOREIGN KEY ("promoted_message_id") REFERENCES "public"."messages"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "draft_previews" ADD CONSTRAINT "draft_previews_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "draft_previews" ADD CONSTRAINT "draft_previews_draft_id_draft_messages_id_fk" FOREIGN KEY ("draft_id") REFERENCES "public"."draft_messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "draft_messages_client_idx" ON "draft_messages" USING btree ("client_id");--> statement-breakpoint
CREATE UNIQUE INDEX "draft_previews_draft_size_unique" ON "draft_previews" USING btree ("client_id","draft_id","size");--> statement-breakpoint
CREATE INDEX "draft_previews_client_draft_idx" ON "draft_previews" USING btree ("client_id","draft_id");