CREATE TABLE "channels" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "channels_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"key" text NOT NULL,
	"code" text NOT NULL,
	"label" text NOT NULL,
	"order_index" integer NOT NULL,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
ALTER TABLE "channels" ADD CONSTRAINT "channels_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "channels_client_key_unique" ON "channels" USING btree ("client_id","key");--> statement-breakpoint
CREATE INDEX "channels_client_code_idx" ON "channels" USING btree ("client_id","code");--> statement-breakpoint
CREATE INDEX "channels_client_order_idx" ON "channels" USING btree ("client_id","order_index");