CREATE TABLE "briefs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "briefs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"slides_file_id" text NOT NULL,
	"label" text,
	"created_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"updated_at" text DEFAULT (to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')) NOT NULL,
	"archived_at" text
);
--> statement-breakpoint
ALTER TABLE "messages" ALTER COLUMN "audience" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "messages" ALTER COLUMN "topic" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN "brief_id" integer;--> statement-breakpoint
ALTER TABLE "briefs" ADD CONSTRAINT "briefs_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "briefs_client_slides_file_unique" ON "briefs" USING btree ("client_id","slides_file_id");--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_brief_id_briefs_id_fk" FOREIGN KEY ("brief_id") REFERENCES "public"."briefs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "messages_client_brief_idx" ON "messages" USING btree ("client_id","brief_id");--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_draft_has_no_audience" CHECK (("messages"."status" = 'DRAFT') = ("messages"."audience" IS NULL));--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_placed_has_topic" CHECK ("messages"."audience" IS NULL OR "messages"."topic" IS NOT NULL);--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_draft_has_no_pmmid" CHECK ("messages"."status" != 'DRAFT' OR "messages"."pmmid" IS NULL);