// The default icon family, and the one complete one: every semantic name in
// the app resolves here. IconName is derived from this table, so a Core family
// can only ever be a subset — it cannot invent a name the default lacks, and
// the default cannot quietly lose one.
//
// Names are semantic, not lucide's: `close` rather than `X`, `delete` rather
// than `Trash2`. That is the whole point of the indirection — the call sites
// say what they mean, and a family swap is a table edit instead of 68 files.
//
// Two lucide aliases collapse here: AlertTriangle/TriangleAlert and
// AlertCircle/CircleAlert are each one icon under two names (old and new), and
// both spellings were in use across the app.

import {
  AlertCircle,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowRightLeft,
  ArrowUp,
  ArrowUpRight,
  BarChart3,
  BookOpen,
  Camera,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Code2,
  Columns3,
  Copy,
  CopyPlus,
  Download,
  ExternalLink,
  EyeOff,
  FileCode,
  FilePlus2,
  FileText,
  Filter,
  FlaskConical,
  GitFork,
  Globe,
  Grid,
  Grip,
  GripHorizontal,
  GripVertical,
  History,
  Image,
  ImageOff,
  Images,
  Info,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Link,
  Link2,
  List,
  Loader2,
  ListTree,
  Lock,
  LogOut,
  MapPin,
  Maximize,
  Maximize2,
  MessageSquare,
  Minus,
  Moon,
  MoreHorizontal,
  Package,
  Palette,
  Pencil,
  PencilRuler,
  Plus,
  PocketKnife,
  Presentation,
  RefreshCw,
  Rocket,
  RotateCcw,
  Rss,
  Save,
  Settings,
  Share2,
  ShieldAlert,
  Square,
  SquarePlus,
  Star,
  Sun,
  Table2,
  Tag,
  Trash2,
  TriangleAlert,
  Type,
  Unlink2,
  Upload,
  Users,
  Video,
  Waypoints,
  X,
} from "lucide-react";
import GoogleDriveIcon from "@/app/_components/GoogleDriveIcon";
import type { IconComponent } from "../types";

export const LUCIDE_ICONS = {
  // interface
  close: X,
  check: Check,
  "check-double": CheckCheck,
  "check-circle": CheckCircle2,
  add: Plus,
  subtract: Minus,
  "add-square": SquarePlus,
  delete: Trash2,
  edit: Pencil,
  design: PencilRuler,
  copy: Copy,
  "copy-add": CopyPlus,
  save: Save,
  filter: Filter,
  more: MoreHorizontal,
  spinner: Loader2,
  settings: Settings,
  lock: Lock,
  hidden: EyeOff,
  info: Info,
  warning: TriangleAlert,
  alert: AlertCircle,
  "shield-alert": ShieldAlert,

  // navigation
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-up-right": ArrowUpRight,
  swap: ArrowRightLeft,
  "external-link": ExternalLink,
  refresh: RefreshCw,
  undo: RotateCcw,
  history: History,
  logout: LogOut,
  expand: Maximize,
  "expand-corners": Maximize2,
  download: Download,
  upload: Upload,
  link: Link,
  "link-alt": Link2,
  unlink: Unlink2,
  share: Share2,

  // views and layout
  dashboard: LayoutDashboard,
  list: List,
  "list-task": LayoutList,
  tree: ListTree,
  fork: GitFork,
  waypoints: Waypoints,
  grid: Grid,
  "grid-tiles": LayoutGrid,
  columns: Columns3,
  table: Table2,
  grip: Grip,
  "grip-vertical": GripVertical,
  "grip-horizontal": GripHorizontal,
  square: Square,

  // content, media, entities
  image: Image,
  images: Images,
  "image-off": ImageOff,
  camera: Camera,
  video: Video,
  "file-text": FileText,
  "file-code": FileCode,
  "file-add": FilePlus2,
  code: Code2,
  text: Type,
  palette: Palette,
  book: BookOpen,
  tag: Tag,
  star: Star,
  comment: MessageSquare,
  pin: MapPin,
  globe: Globe,
  chart: BarChart3,
  archive: Archive,
  "archive-restore": ArchiveRestore,
  package: Package,
  rss: Rss,
  users: Users,
  flask: FlaskConical,
  rocket: Rocket,
  slides: Presentation,
  toolbar: PocketKnife,
  "sun": Sun,
  "moon": Moon,

  // brands
  "google-drive": GoogleDriveIcon,
} satisfies Record<string, IconComponent>;
