/**
 * Generates src/app/_icons/families/core-line.tsx from the Streamline Core
 * Line set (@iconify-json/streamline) using the hand-curated CORE_MAP.
 *
 * Build-time, and the output is committed: the box builds without network, and
 * the 1 MB icon JSON never reaches the bundle — only the ~70 path strings the
 * app actually draws.
 *
 * Run: npx tsx scripts/gen-icons.ts
 */
import { writeFileSync } from "node:fs";
import iconSet from "@iconify-json/streamline/icons.json" with { type: "json" };
import { CORE_MAP } from "../src/app/_icons/core-map";

type IconSetJson = {
  icons: Record<string, { body: string }>;
  aliases?: Record<string, { parent: string }>;
};

const set = iconSet as unknown as IconSetJson;

function bodyOf(name: string): string {
  const direct = set.icons[name];
  if (direct) return direct.body;
  const alias = set.aliases?.[name];
  if (alias) return bodyOf(alias.parent);
  throw new Error(`streamline has no icon "${name}" — fix CORE_MAP`);
}

const ROTATE_CLASS: Record<number, string> = {
  45: "rotate-45",
  90: "rotate-90",
  180: "rotate-180",
  [-90]: "-rotate-90",
};

const PREFIXES = ["", "line-", "triangle-", "square-", "circle-"];

/** Core's Solid names are `<line>-solid` without exception in our 75. Remix is
 *  the ragged one: 64 of Core's 1000 take a prefix instead of the suffix, so we
 *  try those before giving up and leaving the name to lucide. */
function variantName(entry: { line: string; remix?: string | null }, family: Family) {
  if (family === "line") return entry.line;
  if (family === "remix" && entry.remix !== undefined) return entry.remix;
  const suffix = family === "solid" ? "-solid" : "-remix";
  return (
    PREFIXES.map((p) => `${p}${entry.line}${suffix}`).find(
      (n) => set.icons[n] || set.aliases?.[n],
    ) ?? null
  );
}

type Family = "line" | "solid" | "remix";

const FAMILIES: Array<{ family: Family; file: string; exportName: string; label: string }> = [
  { family: "line", file: "core-line.tsx", exportName: "CORE_LINE_ICONS", label: "Core Line" },
  { family: "solid", file: "core-solid.tsx", exportName: "CORE_SOLID_ICONS", label: "Core Solid" },
  { family: "remix", file: "core-remix.tsx", exportName: "CORE_REMIX_ICONS", label: "Core Remix" },
];

for (const { family, file, exportName, label } of FAMILIES) {
  const skipped: string[] = [];
  const entries = Object.entries(CORE_MAP).flatMap(([semantic, entry]) => {
    if (!entry) throw new Error(`empty CORE_MAP entry for ${semantic}`);
    const name = variantName(entry, family);
    if (!name) {
      skipped.push(semantic);
      return [];
    }
    const body = bodyOf(name).replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
    const rotate = entry.rotate ? `, "${ROTATE_CLASS[entry.rotate]}"` : "";
    const key = /^[a-z][a-z0-9]*$/.test(semantic) ? semantic : `"${semantic}"`;
    return [`  ${key}: make(\`${body}\`${rotate}),`];
  });

  const out = `// GENERATED by scripts/gen-icons.ts — do not edit by hand.
// Source: Streamline ${label} (@iconify-json/streamline), CC BY 4.0,
// https://streamlinehq.com. Mapping: src/app/_icons/core-map.ts.
//
// Names absent here fall back to lucide at render time (see core-map.ts).
import type { SVGProps } from "react";
import clsx from "clsx";
import type { IconComponent } from "../types";

/** Core draws on a 14 grid with no inner margin; \`icon--core\` gives back the
 *  optical padding lucide's 24 grid has built in (globals.css). */
function make(body: string, rotate?: string): IconComponent {
  function CoreIcon({ className, ...rest }: SVGProps<SVGSVGElement>) {
    return (
      <svg
        viewBox="0 0 14 14"
        fill="none"
        aria-hidden
        focusable="false"
        {...rest}
        className={clsx("icon--core", rotate, className)}
        dangerouslySetInnerHTML={{ __html: body }}
      />
    );
  }
  return CoreIcon;
}

export const ${exportName} = {
${entries.join("\n")}
} as const;
`;

  writeFileSync(`src/app/_icons/families/${file}`, out);
  console.log(
    `wrote ${file} with ${entries.length} icons` +
      (skipped.length ? ` (no ${family} variant, staying lucide: ${skipped.join(", ")})` : ""),
  );
}

// ---------------------------------------------------------------------------
// Core Pop. Not on Iconify — only in the GitHub repo, under a category folder
// per icon, so the paths come from the git tree API. Its names follow Remix's
// (line-arrow-up-1-remix → line-arrow-up-1), which is why this derives from the
// resolved Remix name instead of guessing a second time.
//
// Pop is NOT currentColor: a fixed navy plus four accent fills. The navy
// becomes var(--icon-ink) so dark mode can lift it (globals.css); the accents
// stay literal, which is the accepted trade-off from the study — a Pop icon
// does not take the rose/emerald status colouring the app paints elsewhere.
const POP_INK = "#0c098c";
const RAW = "https://raw.githubusercontent.com/webalys-hq/streamline-vectors/main/";
const TREE =
  "https://api.github.com/repos/webalys-hq/streamline-vectors/git/trees/main?recursive=1";

async function generatePop() {
  const tree = (await (await fetch(TREE)).json()) as {
    tree?: Array<{ path: string }>;
  };
  if (!tree.tree) throw new Error("github tree API returned no tree");
  const byName = new Map<string, string>();
  for (const f of tree.tree) {
    if (f.path.startsWith("core/pop/") && f.path.endsWith(".svg")) {
      byName.set(f.path.split("/").pop()!.replace(".svg", ""), f.path);
    }
  }

  const skipped: string[] = [];
  const entries: string[] = [];
  for (const [semantic, entry] of Object.entries(CORE_MAP)) {
    if (!entry) continue;
    const remix = variantName(entry, "remix");
    const popName = remix ? remix.replace(/-remix$/, "") : null;
    const path = popName ? byName.get(popName) : undefined;
    if (!path) {
      skipped.push(semantic);
      continue;
    }
    const svg = await (await fetch(RAW + path)).text();
    const body = svg
      .replace(/^[\s\S]*?<svg[^>]*>/, "")
      .replace(/<\/svg>\s*$/, "")
      .replace(/<desc>[\s\S]*?<\/desc>/g, "")
      // Streamline's editor ids are ~20% of Pop's bytes and mean nothing here;
      // worse, duplicated ids across icons on one page are invalid HTML.
      .replace(/\s(?:id|stroke-width)="[^"]*"/g, "")
      .replace(new RegExp(POP_INK, "gi"), "var(--icon-ink)")
      .replace(/\s+/g, " ")
      .trim()
      .replace(/`/g, "\\`")
      .replace(/\$\{/g, "\\${");
    const rotate = entry.rotate ? `, "${ROTATE_CLASS[entry.rotate]}"` : "";
    const key = /^[a-z][a-z0-9]*$/.test(semantic) ? semantic : `"${semantic}"`;
    entries.push(`  ${key}: make(\`${body}\`${rotate}),`);
  }

  const out = `// GENERATED by scripts/gen-icons.ts — do not edit by hand.
// Source: Streamline Core Pop (github.com/webalys-hq/streamline-vectors),
// CC BY 4.0, https://streamlinehq.com. Mapping: src/app/_icons/core-map.ts.
//
// Pop ships fixed colours instead of currentColor. The navy is rewritten to
// var(--icon-ink) so dark mode can lift it; the accent fills stay literal, so
// a Pop icon keeps its own palette where the app paints status colours.
import type { SVGProps } from "react";
import clsx from "clsx";
import type { IconComponent } from "../types";

function make(body: string, rotate?: string): IconComponent {
  function PopIcon({ className, ...rest }: SVGProps<SVGSVGElement>) {
    return (
      <svg
        viewBox="0 0 14 14"
        fill="none"
        aria-hidden
        focusable="false"
        {...rest}
        className={clsx("icon--core icon--pop", rotate, className)}
        dangerouslySetInnerHTML={{ __html: body }}
      />
    );
  }
  return PopIcon;
}

export const CORE_POP_ICONS = {
${entries.join("\n")}
} as const;
`;
  writeFileSync("src/app/_icons/families/core-pop.tsx", out);
  console.log(
    `wrote core-pop.tsx with ${entries.length} icons` +
      (skipped.length ? ` (no pop variant, staying lucide: ${skipped.join(", ")})` : ""),
  );
}

// Not top-level await: tsx transpiles this to CJS.
generatePop().catch((err: Error) => {
  // Pop is the one family that needs network. Keep the committed file rather
  // than truncating it, and say so out loud.
  console.warn(
    `SKIPPED core-pop.tsx — it needs network (${err.message}). ` +
      `The committed file is left as it is.`,
  );
});
