/**
 * Generates src/app/_icons/families/core-line.tsx from the Streamline Core
 * Line set (@iconify-json/streamline) using the hand-curated CORE_MAP.
 *
 * Build-time, and the output is committed: the box builds without network, and
 * the 1 MB icon JSON never reaches the bundle — only the ~70 path strings the
 * app actually draws.
 *
 * Run: npx tsx scripts/gen-icons.ts
 */
import { writeFileSync } from "node:fs";
import iconSet from "@iconify-json/streamline/icons.json" with { type: "json" };
import { CORE_MAP } from "../src/app/_icons/core-map";

type IconSetJson = {
  icons: Record<string, { body: string }>;
  aliases?: Record<string, { parent: string }>;
};

const set = iconSet as unknown as IconSetJson;

function bodyOf(name: string): string {
  const direct = set.icons[name];
  if (direct) return direct.body;
  const alias = set.aliases?.[name];
  if (alias) return bodyOf(alias.parent);
  throw new Error(`streamline has no icon "${name}" — fix CORE_MAP`);
}

const ROTATE_CLASS: Record<number, string> = {
  45: "rotate-45",
  90: "rotate-90",
  180: "rotate-180",
  [-90]: "-rotate-90",
};

const entries = Object.entries(CORE_MAP).map(([semantic, entry]) => {
  if (!entry) throw new Error(`empty CORE_MAP entry for ${semantic}`);
  const body = bodyOf(entry.line).replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  const rotate = entry.rotate ? `, "${ROTATE_CLASS[entry.rotate]}"` : "";
  const key = /^[a-z][a-z0-9]*$/.test(semantic) ? semantic : `"${semantic}"`;
  return `  ${key}: make(\`${body}\`${rotate}),`;
});

const out = `// GENERATED by scripts/gen-icons.ts — do not edit by hand.
// Source: Streamline Core Line (@iconify-json/streamline), CC BY 4.0,
// https://streamlinehq.com. Mapping: src/app/_icons/core-map.ts.
//
// Names absent here fall back to lucide at render time (see core-map.ts).
import type { SVGProps } from "react";
import clsx from "clsx";
import type { IconComponent } from "../types";

/** Core draws on a 14 grid with no inner margin; \`icon--core\` gives back the
 *  optical padding lucide's 24 grid has built in (globals.css). */
function make(body: string, rotate?: string): IconComponent {
  function CoreIcon({ className, ...rest }: SVGProps<SVGSVGElement>) {
    return (
      <svg
        viewBox="0 0 14 14"
        fill="none"
        aria-hidden
        focusable="false"
        {...rest}
        className={clsx("icon--core", rotate, className)}
        dangerouslySetInnerHTML={{ __html: body }}
      />
    );
  }
  return CoreIcon;
}

export const CORE_LINE_ICONS = {
${entries.join("\n")}
} as const;
`;

writeFileSync("src/app/_icons/families/core-line.tsx", out);
console.log(`wrote core-line.tsx with ${entries.length} icons`);
