-- Append SZA _IDF audience set (client_id=8 / Erste). Coexists with existing SZA rows.
-- All rows: product=SZA, buying_platform=adform, status=ACTIVE, version=1,
--   campaign_name + campaign_id shared. order_index 166..180.
BEGIN TRANSACTION;

INSERT INTO audiences
  (client_id, key, name, order_index, status, product, strategy, buying_platform,
   data_source, targeting_type, device, tag, comment, campaign_name, campaign_id,
   lineitem_name, lineitem_id, version)
VALUES
  (8, 'SZA_adaptive_IDF',            'Private Deal - Adaptive IDFusion',            166, 'ACTIVE', 'SZA', 'pro', 'adform', 'adaptive',  'privatedeal', 'all',     'adaptive',            '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-private!con!pro!...!pbu-ron!SZA_adaptive_IDF!v11',            '14728243', 1),
  (8, 'SZA_indamedia_IDF',           'Private Deal - Indamedia IDFusion',           167, 'ACTIVE', 'SZA', 'pro', 'adform', 'indamedia', 'privatedeal', 'all',     'indamedia',           '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-private!con!pro!...!pbu-ron!SZA_indamedia_IDF!v11',           '14728244', 1),
  (8, 'SZA_central_IDF',             'Private Deal - Central IDFusion',             168, 'ACTIVE', 'SZA', 'pro', 'adform', 'central',   'privatedeal', 'all',     'central',             '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-private!con!pro!...!pbu-ron!SZA_central_IDF!v11',             '14728242', 1),
  (8, 'SZA_infinety_IDF',            'Private Deal - Infinety IDFusion',            169, 'ACTIVE', 'SZA', 'pro', 'adform', 'infinety',  'privatedeal', 'all',     'infinety',            '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-private!con!pro!...!pbu-ron!SZA_infinety_IDF!v11',            '14728240', 1),
  (8, 'SZA_telex_IDF',               'Private Deal - Telex IDFusion',               170, 'ACTIVE', 'SZA', 'pro', 'adform', 'telex',     'privatedeal', 'all',     'telex',               '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-private!con!pro!...!pbu-ron!SZA_telex_IDF!v11',               '14728241', 1),
  (8, 'SZA_atmedia_IDF',             'Private Deal - Atmedia IDFusion',             171, 'ACTIVE', 'SZA', 'pro', 'adform', 'atmedia',   'privatedeal', 'all',     'atmedia',             '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-private!con!pro!...!pbu-ron!SZA_atmedia_IDF!v11',             '14728245', 1),
  (8, 'SZA_wlhr-dsk_IDF',            'High reach whitelist IDFusion',               172, 'ACTIVE', 'SZA', 'pro', 'adform', 'open',      'whitelist',   'desktop', 'hrwldsk',             '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-open!con!pro!...!pbu-ron!SZA_wlhr-dsk_IDF!v11',              '14728167', 1),
  (8, 'SZA_wlhr-mob_IDF',            'High reach whitelist IDFusion',               173, 'ACTIVE', 'SZA', 'pro', 'adform', 'open',      'whitelist',   'mobile',  'hrwlmob',             '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-open!con!pro!...!pbu-ron!SZA_wlhr-mob_IDF!v11',              '14728170', 1),
  (8, 'SZA_wlfin-dsk_IDF',           'Finance&Business whitelist IDFusion',         174, 'ACTIVE', 'SZA', 'pro', 'adform', 'open',      'whitelist',   'desktop', 'findsk',              '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-open!con!pro!...!pbu-ron!SZA_wlfin-dsk_IDF!v11',             '14728166', 1),
  (8, 'SZA_wlfin-mob_IDF',           'Finance&Business whitelist IDFusion',         175, 'ACTIVE', 'SZA', 'pro', 'adform', 'open',      'whitelist',   'mobile',  'finmob',              '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-open!con!pro!...!pbu-ron!SZA_wlfin-mob_IDF!v11',             '14728165', 1),
  (8, 'SZA_rtg-allvisitors_IDF',     'All szamlaoldal visitors remarket IDFusion',  176, 'ACTIVE', 'SZA', 'rem', 'adform', 'RTG',       'segment',     'all',     'visitors',            '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-open!con!ret!...!pbu-ron!SZA_rtg-allvisitors_IDF!v11',       '14728365', 1),
  (8, 'SZA_onlszvisitorsLAL',        'Onlineszamla visitors LAL',                   177, 'ACTIVE', 'SZA', 'pro', 'adform', 'open',      'whitelist',   'all',     'onlszvisitorsLAL',    '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-open!con!pro!...!pbu-ron!SZA_onlszvisitorsLAL!v11',          '14728546', 1),
  (8, 'SZA_onlszvisitorsLAL_IDF',    'Onlineszamla visitors LAL IDFusion',          178, 'ACTIVE', 'SZA', 'pro', 'adform', 'open',      'whitelist',   'all',     'onlszvisitorsLAL',    '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-open!con!pro!...!pbu-ron!SZA_onlszvisitorsLAL_IDF!v11',      '14728521', 1),
  (8, 'SZA_wldigisegmobbanking',     'Digiseg Mobile banking',                      179, 'ACTIVE', 'SZA', 'pro', 'adform', 'digiseg',   'segment',     'all',     'wldigisegmobbanking', '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-open!con!pro!...!pbu-ron!SZA_wldigisegmobbanking!v11',       '14729527', 1),
  (8, 'SZA_wldigisegmobbanking_IDF', 'Digiseg Mobile banking ID Fusion',            180, 'ACTIVE', 'SZA', 'pro', 'adform', 'digiseg',   'segment',     'all',     'wldigisegmobbanking', '', '26!1!account!onlineszamlanyitas!onlineszamlanyitas!hu!ebh!mID26-00018!longterm!...!v11', '4037347', 'display!all!cpm!auc!pbu-ron!dsp-open!con!pro!...!pbu-ron!SZA_wldigisegmobbanking_IDF!v11',   '14729540', 1);

COMMIT;
